const tabela = {'PRISMA': {
    'Nome': 'Prisma',
    'Lugares' : '5',
    'Maleiro' : 'Grande',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Valor': '250,00',
    'Radio':'True',
    'marca':'Chevrolet',
    'foto' : 'https://quatrorodas.abril.com.br/wp-content/uploads/2018/02/chevrolet-prisma-advantage.jpg?resize=650,433'
},

'HB': {
    'Nome': 'hb20',
    'Lugares' : '5',
    'Maleiro' : 'Grande',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '250,00',
    'marca':'Hyundai',
    'foto' : 'https://www.webmotors.com.br/imagens/prod/348164/HYUNDAI_HB20_1.0_12V_FLEX_SENSE_MANUAL_34816412251079433.png?s=fill&w=130&h=97&q=70&t=true)'
},

'GOL': {
    'Nome': 'gol',
    'Lugares' : '5',
    'Maleiro' : 'Medio',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'False',
    'Valor': '260,00',
    'marca':'Volkswagen',
    'foto' : 'https://www.cnnbrasil.com.br/wp-content/uploads/sites/12/2021/11/VW-Gol.jpg?w=1200&h=675&crop=1'
},

'LOGAN': {
    'Nome': 'logan',
    'Lugares' : '5',
    'Maleiro' : 'Medio',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'False',
    'Valor': '260,00',
    'marca':'Renault',
    'foto' : 'https://cdn.motor1.com/images/mgl/7xGZq/s1/novo-renault-logan-2022---projecao.webp'
},

'DUSTER': {
    'Nome': 'Duster',
    'Lugares' : '5',
    'Maleiro' : 'Gigante',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Automatico',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '360,00',
    'marca':'Renault',
    'foto' : 'https://brfrance.com.br/uploads/products/versions/colors/duster-intense-22-02-3.png'
},

'VERSA': {
    'Nome': 'Versa',
    'Lugares' : '5',
    'Maleiro' : 'Grande',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '350,00',
    'marca':'Nissan',
    'foto' : 'https://nissan.itavema.com.br/media/catalog/product/cache/1/thumbnail/9df78eab33525d08d6e5fb8d27136e95/n/o/novo_versa_exclusive_1_6_cvt.jpg'

},

'KA': {
    'Nome': 'Ka',
    'Lugares' : '5',
    'Maleiro' : 'Media',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'Flase',
    'Radio':'False',
    'Valor': '340,00',
    'marca':'Ford',
    'foto' : 'https://quatrorodas.abril.com.br/wp-content/uploads/2017/02/1249201065927-e1596820958507.jpeg'
},

'MOBI': {
    'Nome': 'Mobi',
    'Lugares' : '5',
    'Maleiro' : 'Pequeno',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'False',
    'Valor': '300,00',
    'marca':'Fiat',
    'foto' : 'https://atri.com.br/models/mobi/colors/MOBI_PRATA.jpg'
},

'RENEGADE': {
    'Nome': 'Renegade',
    'Lugares' : '5',
    'Maleiro' : 'Gigante',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Automatico',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '360,00',
    'marca':'Jeep',
    'foto' : 'https://www.jeep.pt/content/dam/jeep/crossmarket/model/Renegade-80th-Anniversary/ICE/figurini/Jeep_Renegade_80th_099_granitecrystal_565x330.png'
},

'KWID': {
    'Nome': 'Kwid',
    'Lugares' : '4',
    'Maleiro' : 'pequeno',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '340,00',
    'marca':'Renault',
    'foto' : 'https://brfrance.com.br/uploads/products/versions/colors/kwid-2022-intense-01.png'
},

'UP': {
    'Nome': 'Up',
    'Lugares' : '4',
    'Maleiro' : 'Pequeno',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manuais',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'False',
    'Valor': '200,00',
    'marca':'Volkswagen',
    'foto' : 'https://quatrorodas.abril.com.br/wp-content/uploads/2017/04/novo-up-4.jpg?quality=70&strip=info'
},

'SPIN': {
    'Nome': 'Spin',
    'Lugares' : '7',
    'Maleiro' : 'Media',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Automatico',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '450,00',
    'marca':'Chevrolet',
    'foto' : 'https://www.chevrolet.com.br/content/dam/chevrolet/mercosur/brazil/portuguese/index/crossovers-and-suvs/2021-spin/colorizer/2021-spin-cinza-satin-steel.png?imwidth=960'
},


'DOBLO': {
    'Nome': 'Doblo',
    'Lugares' : '7',
    'Maleiro' : 'Grande',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '500,00',
    'marca':'Fiat',
    'foto' : 'https://revistacarro.com.br/wp-content/uploads/2018/05/doblo.png'
},

'TORO': {
    'Nome': 'Toro',
    'Lugares' : '5',
    'Maleiro' : 'Gigante',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Automatico',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'True',
    'Radio':'True',
    'Valor': '600,00',
    'marca':'Fiat',
    'foto' : 'https://carroesporteclube.com.br/wp-content/uploads/2021/10/Fiat-Toro-Black-Edition.jpg'
},

'SAVEIRO': {
    'Nome': 'Saveiro',
    'Lugares' : '2',
    'Maleiro' : 'SuperGigante',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manual',
    'Arcondicionado': 'False',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '600,00',
    'marca':'Volkswagen',
    'foto' : 'https://beta.alpes.one/storage/app/uploads/public/5fe/ce8/e46/5fece8e464a74236404978.jpg'
},

'FIORINO': {
    'Nome': 'Fiorino',
    'Lugares' : '2',
    'Maleiro' : 'SuperGigante',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manual',
    'Arcondicionado': 'False',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '600,00',
    'marca':'Fiat',
    'foto' : 'https://cdn.motor1.com/images/mgl/9mZyYl/s3/fiat-fiorino-2022.jpg'
},

'CORSA': {
    'Nome': 'Corsa',
    'Lugares' : '5',
    'Maleiro' : 'Medio',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manual',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '150,00',
    'marca':'Chevrolet',
    'foto' : 'https://static3.tcdn.com.br/img/img_prod/232876/kit_farol_de_milha_corsa_classic_corsa_pick_up_auxiliar_neblina_botao_original_23297_6_6c4e81d9c2ad5ad16bf7f2f2a223c5c7.jpg'
},

'CELTA': {
    'Nome': 'Celta',
    'Lugares' : '4',
    'Maleiro' : 'Pequeno',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manual',
    'Arcondicionado': 'False',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '100,00',
    'marca':'Fiat',
    'foto' : 'https://img1.icarros.com/dbimg/galeriaimgmodelo/8/47578_1.jpg'
},

'PALIO': {
    'Nome': 'Palio',
    'Lugares' : '4',
    'Maleiro' : 'Pequena',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'ELetricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '150,00',
    'marca':'Fiat',
    'foto' : 'https://cdn.motor1.com/images/mgl/yxXOe/s1/fiat-palio-14-e-16.webp'
},

'JETA': {
    'Nome': 'Jeta',
    'Lugares' : '5',
    'Maleiro' : 'Medio',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Manual',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '170,00',
    'marca':'Volkswagen',
    'foto' : 'https://4.bp.blogspot.com/-ErpcC4P0EXw/WU8MhMsO83I/AAAAAAAABUg/w7bu2UdEBvw-K1WpB9_RZjDKd7Ht8ORKgCLcBGAs/s1600/JETA.jpg'
},

'UNO': {
    'Nome': 'Uno',
    'Lugares' : '5',
    'Maleiro' : 'Pequeno',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Manual',
    'Travas' : 'Manual',
    'Arcondicionado': 'False',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '100,00',
    'marca':'Fiat',
    'foto' : 'https://s2.glbimg.com/YRJMoW8zd9z7O--njWeMfloClv4=/0x0:620x400/600x0/smart/filters:gifv():strip_icc()/i.s3.glbimg.com/v1/AUTH_cf9d035bf26b4646b105bd958f32089d/internal_photos/bs/2020/w/1/nrsDdXTpSRnonpdBJERA/2015-03-19-uno2.png'
},

'ONIX': {
    'Nome': 'Onix',
    'Lugares' : '5',
    'Maleiro' : 'Grande',
    'Quilometragem' : 'Ilimitada',
    'Cambio' : 'Manual',
    'Direção' : 'Eletrica',
    'Travas' : 'Eletricas',
    'Arcondicionado': 'True',
    'Multimidia': 'False',
    'Radio':'True',
    'Valor': '200,00',
    'marca':'Chevrolet',
    'foto' : 'https://cdn.awsli.com.br/600x450/562/562407/produto/30482218/0d12f71d80.jpg'
}

}